use_frameworks!

target 'TestModul_Example' do
  pod 'TestModul', :path => '../'

  target 'TestModul_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
